### ISSUE TITLE
Player Shoot Script 

### ISSUE THREAD

**Issue by Atharv23m** [opencodeiiita/ZoombieMania-#10]
Now as the Player basic movement is full functioning,
Lets add the shooting mechanism.
### Procedure 
1. Create a small sphere as Prefab (our bullet).
2. Edit the Player_Shoot Script to implement shooting mechanism.
3. [HINT] https://www.youtube.com/watch?v=EwiUomzehKU Take reference from here, 
4. Just implement Shooting script and a bullet lifespan script, Dont write any code to destroy objects on collision yet.
Best of luck destroying some zombies !!

**Comment by TheDivineAurora** [comment]
claim

**Comment by Atharv23m** [comment]
Assigned to @TheDivineAurora  and completed
