### ISSUE TITLE
Player Dash Script 

### ISSUE THREAD

**Issue by Atharv23m** [opencodeiiita/ZoombieMania-#11]
Lets add some more movement mechanisms to our Player (So he can be the ultimate ZoombieSlayer!)
We want our player to dash in the direction it is looking.
### Procedure 
1. Create a script named Player_Dash and attach it to player 
2. Add the code for dashing using 'SPACEBAR'.
3. Also add a short cooldown to stop infinite dashing.
4. [HINT] https://www.youtube.com/watch?v=vTNWUbGkZ58 u can easily implemet dash from here.
5. Think about how you can add a cooldown  to dash. 
6. Declare a public float variable for cooldown timer

**Comment by aasthaaaa7** [comment]
claim

**Comment by Atharv23m** [comment]
Issue assigned to @aasthaaaa7
