### ISSUE TITLE
Adding Enemies 

### ISSUE THREAD

**Issue by Atharv23m** [opencodeiiita/ZoombieMania-#13]
Lets get to the fun and a bit advanced part now !! 
Adding enemies to our game.
### Procedure 
1. Create a Enemy model (can be a simple capsule or something unique ?), and save it as a Prefab.
2. In the Test Scene, Set up NavMesh AI for Enemy.
3. Bake the Plane as Navmesh Plane and Set Enemy as NavMesh Agent
4. Add a Enemy script that makes enemy follow Player.
5. [HINT] https://www.youtube.com/watch?v=pFGjrFSoSBY

**Comment by TheDivineAurora** [comment]
claim

**Comment by Atharv23m** [comment]
Issue assigned to @TheDivineAurora
