### ISSUE TITLE
Add Ammo to Player's Gun

### ISSUE THREAD

**Issue by Atharv23m** [opencodeiiita/ZoombieMania-#14]
Lets add ammo and reload mechanism to Player's Gun.
1. Add a Canvas and add a TextMeshPro to display the no. of bullets
2. Lets have a max capacity of 20 bullets for now.
3. The gun will reload automatically after 5 seconds of inactivity (not firing the gun).
4. Edit the Player_Shoot script to implement the following changes and link everything to UI.
5. You are free to add something more creative.
6. [HINT] https://www.youtube.com/watch?v=kAx5g9V5bcM

**Comment by aasthaaaa7** [comment]
claim

**Comment by Atharv23m** [comment]
Issue assigned to @aasthaaaa7
