### ISSUE TITLE
Camera Script 

### ISSUE THREAD

**Issue by Atharv23m** [opencodeiiita/ZoombieMania-#17]
Our game needs a camera rework !!
###Procedure 
1. Create a script Camera_Follow and attach it to Main Camera.
2. Add a basic LookAt() Player functionality and Player following mechanism.
3. You are free to be as creative as possible to find the best solution 
4. Try to experiment with TPP perspective as well if it suits the game.

**Comment by TheDivineAurora** [comment]
claim

**Comment by Atharv23m** [comment]
Assigned to @TheDivineAurora
