### ISSUE TITLE
Zombie Death Script

### ISSUE THREAD

**Issue by Atharv23m** [opencodeiiita/ZoombieMania-#20]
A gun's useless if it doesn't kill, So lets deal some damage.
### Changes to be done 
1. Add a int health to zombie script. (default it to 5 for now)
2. Detect collision with bullets, If bullet hits the zombie, decrement health counter. 
3. Once health reaches 0 destroy the zombie.
4. [HINT] Tag the bullets and use OnCollision events

**Comment by aasthaaaa7** [comment]
claim

**Comment by Atharv23m** [comment]
Assigned to @aasthaaaa7
