### ISSUE TITLE
Improving the TPP mechanism 

### ISSUE THREAD

**Issue by Atharv23m** [opencodeiiita/ZoombieMania-#26]
Get ready !!
### Improvements 
- Add auto mode to shoot bullets while holding Fire1.
- Addition of crosshair. 
- Hide the Cursor and lock it center of screen.
- The player's movement should be independent of player's rotation or camera direction.
- Fixing the Dash script.
- Smooth out Player's movement (add accelaration and damping).
- Feel free to add more changes to perfect out character controller.

**Comment by TheDivineAurora** [comment]
claim

**Comment by Atharv23m** [comment]
Assigned to @TheDivineAurora

**Comment by sushantk1274** [comment]
claim
