### ISSUE TITLE
Enemy Spawn Manager 

### ISSUE THREAD

**Issue by Atharv23m** [opencodeiiita/ZoombieMania-#27]
Endless waves of zombiess !!!!
### Procedure 
1. Create a empty GameObject EnemySpawnManager.
2. Add a script to it that will spawn Enemy continously.
3. Add the float for time interval, the enemy Prefab will instantiate at every interval.
4. The enemy will spawn at transform of EnemySpawnManager.

**Comment by aasthaaaa7** [comment]
claim

**Comment by Atharv23m** [comment]
Assigned to @aasthaaaa7
