### ISSUE TITLE
Player Health 

### ISSUE THREAD

**Issue by Atharv23m** [opencodeiiita/ZoombieMania-#28]
Our Player is not invincible !
1. Add a Player Health bar.
2. Create a UI Health bar and add it to the canvas.
3. It should increase/decrease acc to the player's health.
4.  Player will take damage from zombies. 
5. Adjust the damage accordingly so its easy to test out.

**Comment by aasthaaaa7** [comment]
claim

**Comment by aasthaaaa7** [comment]
claim

**Comment by Atharv23m** [comment]
Assigned to @aasthaaaa7

**Comment by sushantk1274** [comment]
claim
