### ISSUE TITLE
Player Look Script

### ISSUE THREAD

**Issue by Atharv23m** [opencodeiiita/ZoombieMania-#3]
This script will control where the player will look and shoot.
We will have the player look at the mouse cursor present in game thus we can control the shooting direction by mouse. 
### Procedure 
1. Open the Test Scene in the Assets/Scenes folder.
2. Open the Player_Shoot script. 
3. Write your code, The script should work as - 
- The Player's front should always face towards the mouse cursor in the game and should Update its rotation as cursor moves.
- [Hint] Use Transform.LookAt() 
4. Test the code in Test Scene.

**Comment by aasthaaaa7** [comment]
claim

**Comment by Atharv23m** [comment]
Completed
