### ISSUE TITLE
Improve Shooting 

### ISSUE THREAD

**Issue by Atharv23m** [opencodeiiita/ZoombieMania-#32]
We lack precise aiming for our player. 
The issue arises due to fact that 
![image](https://user-images.githubusercontent.com/96980038/210132252-f57cbdd6-8198-497a-97e3-e06c00f96025.png)
We aim using a raycast from camera, lets say i aim a zombie (green ray),
But as Camera is farther away from the player, the ray actually doesn't hit zombie, but hits a further point (red ray).
The player then shoots the wrong position(black ray) missing the target we wanted to shoot.
Let's see how you fix the issue.

**Comment by TheDivineAurora** [comment]
Claim

**Comment by Atharv23m** [comment]
Assigned to @TheDivineAurora
