### ISSUE TITLE
Pause Menu 

### ISSUE THREAD

**Issue by Atharv23m** [opencodeiiita/ZoombieMania-#33]
As Title suggests
- Create a new Canvas for Pause Screen
- When u press Esc, the game should pause and Pause Screen Canvas should enable.
- It would contain 2 buttons : Resume and Restart
- Resume : The game resumes
- Restart : Just create a button for now, we will add functionality in future.

**Comment by aasthaaaa7** [comment]
claim

**Comment by Atharv23m** [comment]
Assigned to @aasthaaaa7
