### ISSUE TITLE
Zoombie

### ISSUE THREAD

**Issue by Atharv23m** [opencodeiiita/ZoombieMania-#35]
### Lets add a real zombie 
https://assetstore.unity.com/packages/3d/characters/humanoids/zombie-30232#description
- Import the zombie asset from link provided.
- Replace the existing model with the asset.
-  Setup the animation and sync the asset with the current game
-  Create a custom animation controller and add custom parameters so as to adjust animation accordingly.

**Comment by aasthaaaa7** [comment]
claim

**Comment by Atharv23m** [comment]
The asset link has been updated @aasthaaaa7
