### ISSUE TITLE
Moving Platform Script 

### ISSUE THREAD

**Issue by Atharv23m** [opencodeiiita/ZoombieMania-#6]
Write a basic code for a platform to oscillate between two points P1 and P2.
![image](https://user-images.githubusercontent.com/96980038/208295598-42fc443a-29a3-4f6a-8602-92e04447fbda.png)
### Procedure 
1. Open Moving Platform Scene from Scenes folder.
2. Check out the Platform Gameobject, and the Platform_Movement script attached. 
3. It has 2 Transform variables P1 and P2 which represent the point between which it will move/oscillate.
4. Write the code in the Platform_Movement  script for the following functionality.
5. Use Speed variable to control its speed and add more parameters if necessary.
6. Also move the Platform_Movement script from Assets/ to Assets/Scripts folder.
7. This will be added to our Main scene once fully functioning as obstacles.

**Comment by aasthaaaa7** [comment]
claim

**Comment by aasthaaaa7** [comment]
claim

**Comment by TheDivineAurora** [comment]
claim

**Comment by Atharv23m** [comment]
Assigned to @TheDivineAurora and completed
